### ISSUE TITLE
RC9 ODIN LUA

### ISSUE THREAD

**Issue by Clynikal** [heliorc/imuf-release#11]
LUA not working 
Can’t see issue in open or closed, just making it official. 

Tried:
inverted/uninverted hardware
CLI "set serialrx_inverted = off" 
"set tlm_inverted = off" 
"set tlm_halfduplex = off

Still no worky

**Comment by Clynikal** [comment]
I didn’t mean to write RC9 in the title

**Comment by Clynikal** [comment]
Fport tested ok

**Comment by orneryd** [comment]
We are aware of the LUA script issue and will be updating that soon.
