### ISSUE TITLE
Please widen the release form IMU-F !!!

### ISSUE THREAD

**Issue by adrianmiriuta** [heliorc/imuf-release#7]
Could you please release a separate hex for the IMU-F,
and a documentation how to glue it to a custom BUF build (create the aggregate).

I would gladly help debug BUF code for HELIOSPRING,
but, my hands are tied.

**Comment by denovich** [comment]
I second the motion

**Comment by orneryd** [comment]
we are going to be providing online updates after ODIN is released instead of just separating the binary  :)
