### ISSUE TITLE
IMUF quaternion degradation

### ISSUE THREAD

**Issue by adrianmiriuta** [heliorc/imuf-release#9]
On longer flights (6-8 minutes)
HEADADJUST does not reset yaw drift to 0°
that means imufQuat is degraded  quaternionModulus(imufQuat ) != 1  (no longer a unit quaternion).
that is very bad !

**Comment by adrianmiriuta** [comment]
@kidBrazil 
@orneryd 

I managed to flash the 
PR: IMUF quaternion degradation DEBUG #138
on a HELIOSPRING  with IMUF 106
and got the proof
the quaternionModulus(&qAttitude) value at flight end is 0.992  !
take a look to debug[0].
This is not OK !
do you want to normalize it in the IMUF code ? (it should be fixed there !!!)
or should  I supply a patch for  Butterflight 3.5.1 [ Release Candidate ]  ?

![screenshot from 2018-05-11 18-39-38](https://user-images.githubusercontent.com/29194202/39936277-4152a9dc-554c-11e8-9e6c-a254a476d78c.png)

**Comment by orneryd** [comment]
I Think @adrianmiriuta fixed this in a recent PR to butterflight. Thanks, Adrian!

**Comment by adrianmiriuta** [comment]
@orneryd 
it is only a external patch,
it should be fixed by a quaternion normalization in the IMUF code !
